import '@/styles/globals.css'
import type {AppProps} from 'next/app'
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function App({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>HexaStudio | Chistoph Koschel</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <Component {...pageProps} />
        </>
    );
}
